fix utility output

diff --git a/crd-extractor/crd-extractor b/crd-extractor/crd-extractor
--- a/crd-extractor/crd-extractor
+++ b/crd-extractor/crd-extractor
@@ -2,8 +2,14 @@
 
 # Check if python3 is installed
 if ! command -v python3 &> /dev/null; then
-    printf "python3 is required for this plugin, and is not installed on your machine"
-    printf "please visit https://www.python.org/downloads/ and install it"
+    printf "python3 is required for this utility, and is not installed on your machine"
+    printf "please visit https://www.python.org/downloads/ to install it"
+    exit 1
+fi
+# Check if kubectl is installed
+if ! command -v python3 &> /dev/null; then
+    printf "kubectl is required for this utility, and is not installed on your machine"
+    printf "please visit https://kubernetes.io/docs/tasks/tools/#kubectl to install it"
     exit 1
 fi
 
@@ -33,9 +39,10 @@ python3 $TMP_CRD_DIR/openapi2jsonschema.py $TMP_CRD_DIR/*.yaml
 
 if [ $? == 0 ]; then
     printf "Successfully converted $NUM_OF_CRDS CRDs to JSON schema\n"
-    printf "To execute a Datree policy check against your CRs - run 'datree test --schema-location $HOME/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json /path/to/file'\n"
-    printf "\nWould you like your public CRs to be checked automatically in the future? No problem! Add your schemas to our CRD-catalog and help us support popular CRs in future Datree policy checks :)\n"
-    printf "For more information visit https://www.github.com/datreeio/crds-catalog \n"
+    
+    printf "\nTo validate a CR using various tools, run the relevant command:\n"
+    printf "\n- kubeconform:\n\$kubeconform -summary -output json -schema-location default -schema-location '$HOME/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' /path/to/file\n"
+    printf "\n- datree:\n\$datree test --schema-location $HOME/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json /path/to/file\n\n"
 fi
 
 rm -rf $TMP_CRD_DIR
