fix dependency checks

diff --git a/crd-extractor/crd-extractor b/crd-extractor/crd-extractor
--- a/crd-extractor/crd-extractor
+++ b/crd-extractor/crd-extractor
@@ -7,10 +7,25 @@ if ! command -v python3 &> /dev/null; then
     exit 1
 fi
 # Check if kubectl is installed
-if ! command -v python3 &> /dev/null; then
+if ! command -v kubectl &> /dev/null; then
     printf "kubectl is required for this utility, and is not installed on your machine"
     printf "please visit https://kubernetes.io/docs/tasks/tools/#kubectl to install it"
     exit 1
+fi
+
+# Check if the pyyaml module is installed
+if ! pip3 show pyyaml &> /dev/null; then
+    printf "the python3 module 'yaml' is required, and is not installed on your machine.\n"
+    #printf "would you like to install it? y/n"
+
+    while true; do
+        read -p "Do you wish to install this program? " yn
+        case $yn in
+            [Yy]* ) pip3 install pyyaml; break;;
+            [Nn]* ) echo "Exiting..."; exit;;
+            * ) echo "Please answer yes or no.";;
+        esac
+    done
 fi
 
 # Create temp folder for CRDs
